apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key
  namespace: airflow
type: Opaque
data:
  value: 'dTRfQVN2cGRma0p6UzNvN216aVVnQTFFcW5uOGp4b3dmdzYyblhiVXU0Yz0='
  # value: "7T512UXSSmBOkpWimFHIVb8jK6lfmSAvx4mO6Arehnc==" 
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver-secret-key
  namespace: airflow
type: Opaque
data:
  value: "YmxhYmxkamFmamlvZDtzYWZqaWRzb2E7ZnNh"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: airflow
type: Opaque
data:
  admin-password: UFJWRWx5RExuUQ==
  username: YWlyZmxvdy1hc3Nlc3NtZW50LXVzZXI=
  password: NnREb2pocmRtSg==